template: containers
configuration:
  Containers:
  - Image: gcr.io/instruqt/shell-docker:latest
    Name: shell
    Ports:
    - Exposed: true
      Name: shell
      Port: 8080
    Privileged: true
    Resources:
      Memory: 128
