#!/usr/bin/env bash -s
# Check if the hello-world container was run.
HELLO_ID=$(docker ps -aq --filter ancestor=hello-world --filter status=exited)
if [[ -z $HELLO_ID ]]; then
  echo "DIAG: hello-world was not run"
  exit 1
fi
