#!/bin/bash
set +e

touch /script-started

for i in $(seq 1 30);
do
  docker version  >/dev/null 2>&1
  if [[ $? -eq 0 ]]; then
      touch /script-breaking
      break
  fi
  touch /script-sleeping$i
  sleep 1
done
docker pull hello-world:latest

touch /script-finished
