#!/bin/ash
#
CONTAINER_ID=$(docker ps -aq --filter status=exited --filter ancestor=alpine --filter name=oscar)
if [[ -z $CONTAINER_ID ]]; then
  echo "DIAG: There is no Alpine container named 'oscar' with status 'exited'"
  exit 1
fi

CONTAINER_ID=$(docker ps -aq --filter status=exited --filter ancestor=alpine --filter name=crying)
if [[ -z $CONTAINER_ID ]]; then
  echo "DIAG: There is no Alpine container named 'crying' with status 'exited'"
  exit 1
fi


exit 0
