#!/bin/bash
# Check that an Alpine container named 'oscar' is present with status exited
CONTAINER_NAMES=( "oscar" "hammertime" )

for CONTAINER in "${CONTAINER_NAMES[@]}"; do
  CONTAINER_ID=$(docker ps -aq --filter status=exited --filter ancestor=alpine --filter name=$CONTAINER)
  if [[ -z $CONTAINER_ID ]]; then
    echo "DIAG: There is no Alpine container named '${CONTAINER}' with status 'exited'"
    exit 1
  fi
done

exit 0
